import sys
sys.platform

import os

os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')
os.startfile('notepad.exe')
os.startfile("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe")
os.startfile('https://youtube.com')
os.startfile('calc.exe')

